### ISSUE TITLE
Have you tried middleman? :)

### ISSUE THREAD

**Issue by ssaunier** [BCoulange/Nicotupev2#1]
https://news.ycombinator.com/item?id=4928389

**Comment by BCoulange** [comment]
Nope et ce truc étant un peu au point mort faudra que je regarde. En fait je m'étais pas mal amusé a automatiquement créer des imagettes au bon format et noir et blanc pour des pages (des choses qui se font plutot bien en css...) Au final une fois créé, c'était plutot simple à utilliser
